### ISSUE TITLE
Suggestion: drop git submodule

### ISSUE THREAD

**Issue by ewels** [ScilifelabDataCentre/Data-Delivery-System#401]
Small suggestion, but I suspect that you don't really need the git submodule `DS_CLI` in this repository. If both packages are installed under their own namespaces then they should be able to import one another. I feel that removing the symlink and keeping the two code bases more separate would be better in the long run.

If it's important to keep them in sync then you can pin the cli package version in this repo's installation requirements.

If you think that they should really be kept together, then it might be more suitable to have them in the same repo together.

**Comment by inaod568** [comment]
Yes, we actually discussed this a couple of days ago. We will remove the submodule. 👍🏻

**Comment by inaod568** [comment]
Fixed in `dev`!
